services:
  db:
    image: alfred-db
    build:
      context: ./db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  app:
    image: go-alfred
    build:
      context: ./
    volumes:
      - ./:/app
    restart: always
    environment:
      - PORT=8080
      - BOT_TOKEN=token
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
