CREATE TABLE IF NOT EXISTS "public"."chats" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(
        SEQUENCE NAME "public"."chats_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    "type" "text" NOT NULL,
    "key_version" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."dinners" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."dinners_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    "date" "date" NOT NULL,
    "chat_id" bigint NOT NULL REFERENCES "public"."chats"("id") ON DELETE CASCADE,
    "yes" "text"[] NOT NULL,
    "no" "text"[] NOT NULL,
    "message_ids" bigint[] NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."secrets" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."secrets_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    ),
    "key" "text" NOT NULL,
    "value" "text" NOT NULL,
    "chat_id" bigint NOT NULL REFERENCES "public"."chats"("id") ON DELETE CASCADE
);
