alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: PORT
  scope: RUN_AND_BUILD_TIME
  value: "8080"
- key: BOT_TOKEN
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:sMxjwYDZ/BwZdj0K1Csjsi1euxForNS+:ba5Sh/KqBKrlFf8JYNl3czfViE7L7yNAOS/LayJdbanqGtQtC/Fx3BG4D3sqZgRUFs9Fu8FnRpdHudqqqLQ=]
- key: DB_USER
  scope: RUN_AND_BUILD_TIME
  value: postgres.svgdfzlmmvqkhudikzup
- key: DB_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:3q6sQ0EH9W5zGWFQnvXAMLrLgRjGmZ7H:0yQJt3WfiXi1AiygKBgJeANAEsn9zGwdV96me2lv7Kg=]
- key: DB_HOST
  scope: RUN_AND_BUILD_TIME
  value: aws-0-ap-southeast-1.pooler.supabase.com
- key: DB_PORT
  scope: RUN_AND_BUILD_TIME
  value: "5432"
- key: DB_NAME
  scope: RUN_AND_BUILD_TIME
  value: postgres
- key: TELEGRAM_TEST_SERVER
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: GO_ENV
  scope: RUN_AND_BUILD_TIME
  value: "production"
- key: MASTER_KEY_VERSION
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: MASTER_KEY_V1
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:hckGkaHI4lhogyIU2GIhh7vJMB1r0Ds/:5WHOYyGGgLyg8f5tToTf+J8iM1xcQu6/MYo5XbP+wmn/YRSWXyYmC1Lq9aSAVEOGd0tNgFx9LJg3M5vO]
- key: WEB_APP_URL
  scope: RUN_AND_BUILD_TIME
  value: "t.me/alfred_tan_bot/startapp"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: alvinhuhhh-go-alfred
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: go-alfred-dev
region: sgp
services:
- http_port: 8080
  image:
    registry: alvinhuhhh
    registry_type: GHCR
    repository: go-alfred
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: alvinhuhhh-go-alfred