alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: go-alfred-dev
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: go-alfred-dev
region: sgp
services:
- envs:
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"
  - key: BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:sw1qNrA3HHXc57ZwLjqd4rNJIgq/GXQ3:WoxGPgk9I9clF6UGaDFBmWMviAU8gq5tZ5SDsgv4EdNi8rPtH3nMf09T3650whLGPAEXDvtIEKEi6Ovr0do=]
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
    value: postgres
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:ZhNQaMfjUx779LNVNUZcgS17ZCBw+LjH:7cCgiaWQcHIpOC+MS5GeIJHReEjD/8YhkhxSig3aBYs=]
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: db.inhapokrmngzktjvhlju.supabase.co
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: "5432"
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: postgres
  http_port: 8080
  image:
    registry: alvinhuhhh
    registry_type: GHCR
    repository: go-alfred-api
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: go-alfred-dev
