name: UI Image Build, Publish and Deploy to fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: ./ui
          push: true
          tags: ghcr.io/${{github.repository}}-ui:latest

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
        working-directory: ui
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}